# minqlbot - A Quake Live server administrator bot.
# Copyright (C) Mino <mino@minomino.org>

# This file is part of minqlbot.

# minqlbot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# minqlbot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with minqlbot. If not, see <http://www.gnu.org/licenses/>.

import minqlbot

class docs(minqlbot.Plugin):
    def __init__(self):
        super().__init__()
        self.add_command("gencmd", self.cmd_gencmd, permission=5, usage="[excluded_plugins]")

    def cmd_gencmd(self, players, msg, channel):
        """Generate a command list based on currently loaded plugins in markdown."""
        if len(msg) > 1:
            excluded = [s.lower() for s in msg[1:]]
        else:
            excluded = []

        cmds = {}
        for cmd in minqlbot.COMMANDS.commands:
            if cmd.plugin.__class__.__name__ in excluded:  # Skip excluded plugins.
                continue

            if cmd.permission not in cmds:
                cmds[cmd.permission] = [cmd]
            else:
                cmds[cmd.permission].append(cmd)

        out = (
            "### Commands\n"
            "The command system is based on permission levels. A player will have a permission level\n"
            "of **0** by default. A player with level **1** can execute commands for level **1** and\n"
            "below. A level **2** player can execute level **2**, **1** and **0** commands, and so on.\n"
            "\n\n"
            )
        
        for perm in sorted(cmds.keys()):
            out += "*   Permission level **{}**\n\n".format(perm)
            for cmd in sorted(cmds[perm], key=lambda x: x.plugin.__class__.__name__):
                out += "    *   **`{}`**".format(minqlbot.COMMAND_PREFIX + cmd.name[0])
                if len(cmd.name) > 1:  # Aliases?
                    out += " (alternatively "
                    for alias in cmd.name[1:]:
                        out += "`{}`, ".format(minqlbot.COMMAND_PREFIX + alias)
                    out = out[:-2] + ")"
                out += " from *{}*\n\n".format(cmd.plugin.__class__.__name__)
                
                # Docstring.
                if cmd.handler.__doc__:
                    out += "        {}\n\n".format(cmd.handler.__doc__)

                # Usage
                if cmd.usage:
                    out += "        *Usage*: `{} {}`\n\n" \
                        .format(minqlbot.COMMAND_PREFIX + cmd.name[0], cmd.usage)
        
        out += "*Automatically generated by [minqlbot {}](https://github.com/MinoMino/minqlbot)*" \
            .format(minqlbot.version())

        with open("python\\command_list.md", "w") as f:
            f.write(out)

        channel.reply("^7Command list generated!")
